import "./globals.css";
import { Lato } from "next/font/google";
import SmoothScrolling from "./SmoothScrolling";
import { Topbar } from "./layouts/topbar/topbar";
import Navbar from "./layouts/navbar/navbar";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

config.autoAddCss = false;

export const metadata = {
  title: "RBC Cleaning",
  description: "Generated by create next app",
};

const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato",
  weight: ["300", "400", "700", "900"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lato.className}`}>
        <Topbar />
        <Navbar />
        <SmoothScrolling>
          <div>{children}</div>
        </SmoothScrolling>
      </body>
    </html>
  );
}
