import "./globals.css";
import { Lato, Inter } from "next/font/google";
import SmoothScrolling from "./SmoothScrolling";
import { Topbar } from "./layouts/topbar/topbar";
import Navbar from "./layouts/navbar/navbar";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Footer from "./layouts/footer/footer";
import Providers from "./components/ProgressBarProvider/ProgressBarProvider";

config.autoAddCss = false;

export const metadata = {
  title: "RBC Cleaning",
  description: "Generated by create next app",
};

const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato",
  weight: ["300", "400", "700", "900"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${inter.variable}`}>
        <Topbar />
        <Providers>
          <Navbar />
          <SmoothScrolling>
            <div>{children}</div>
          </SmoothScrolling>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
